# The feedforward neural network model for learning PageRank

In [1]:
import time
from mygraph import MyGraph
from helpers import *

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

## Loading the dataset from numpy files

In [3]:
# Pageank as the target or label data
target_pagerank = np.load("fb_media_pages_pageranks.npy", mmap_mode=None, allow_pickle=False, fix_imports=True, encoding='ASCII')
target_pagerank[0]

array([4.26055693e-05])

In [4]:
# scaling the PageRank data
target_pagerank = target_pagerank * 24000
target_pagerank[0]

array([1.02253366])

In [5]:
target_pagerank.shape

(27917, 1)

In [6]:
# the order 5 NFDC matrix as the feature set
matrix_1 = np.load("fb_media_pages_NDFC_matrix_r1_3_sta1_max70_rad5.npy", mmap_mode=None, allow_pickle=False, fix_imports=True, encoding='ASCII')

In [7]:
matrix_1.shape

(27917, 6, 23)

In [8]:
matrix_1[111]

array([[0.      , 0.      , 0.      , 2.      , 2.      , 0.      ,
        1.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
        0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
        0.      , 0.      , 0.      , 0.      , 0.      ],
       [0.6     , 0.      , 0.2     , 2.8     , 1.6     , 0.      ,
        1.      , 0.4     , 0.4     , 0.      , 0.2     , 0.      ,
        0.      , 0.      , 0.      , 0.      , 0.2     , 0.      ,
        0.      , 0.      , 0.      , 0.      , 0.      ],
       [1.      , 0.583333, 0.333333, 1.75    , 2.916667, 3.583333,
        4.166667, 4.166667, 4.666667, 2.5     , 1.5     , 0.916667,
        0.75    , 0.333333, 0.416667, 0.25    , 0.583333, 0.083333,
        0.      , 0.166667, 0.      , 0.083333, 0.      ],
       [0.252941, 0.514706, 0.594118, 1.326471, 1.461765, 2.467647,
        2.626471, 3.364706, 3.952941, 3.4     , 2.897059, 1.888235,
        1.714706, 1.25    , 1.052941, 0.479412, 1.082353, 0.208824,
       

In [9]:
matrix_1 = matrix_1.reshape(27917,-1)
matrix_1.shape

(27917, 138)

# Converting the data into pytorch tenors

In [10]:
features = torch.from_numpy(matrix_1)
targets = torch.from_numpy(target_pagerank)
features.shape, targets.shape

(torch.Size([27917, 138]), torch.Size([27917, 1]))

In [11]:
# Activating the automatic gradient 
features.requires_grad_(True)
targets.requires_grad_(True)

tensor([[1.0225],
        [0.9398],
        [0.8766],
        ...,
        [0.4565],
        [0.9406],
        [0.9156]], dtype=torch.float64, requires_grad=True)

In [12]:
# Shuffling and dividing the indecies
n_samples = features.shape[0]
n_test = 7917
shuffled_ind = torch.randperm(n_samples)
train_ind = shuffled_ind[:-n_test]
test_ind = shuffled_ind[-n_test:]
# Dividing features and targets into tain and test sets
train_features = features[train_ind]
test_features = features[test_ind]
train_targets = targets[train_ind]
test_targets = targets[test_ind]
train_features.shape, test_features.shape, train_targets.shape, test_targets.shape

(torch.Size([20000, 138]),
 torch.Size([7917, 138]),
 torch.Size([20000, 1]),
 torch.Size([7917, 1]))

## A function for dividing train data into batches

In [13]:
# dividing train_features and train_targets into batches
def next_batch(train_features, train_targets, batch_size=100):
    num_features = train_features.shape[0]
    # Shuffling
    shuffled_ind = torch.randperm(num_features)
    shuffled_train_features = train_features[shuffled_ind]
    shuffled_train_targets = train_targets[shuffled_ind]
    # Dividing
    i = 0
    while i < num_features:
        i += batch_size
        yield (shuffled_train_features[i-batch_size:i], shuffled_train_targets[i-batch_size:i])
    return

## The feedforward neural network model

In [14]:
# The Feedforward Neural Network 
class FFNN_model(nn.Module):
    def __init__(self):
        super().__init__()
        num_features = features.shape[1]
        self.fc1 = nn.Linear(num_features, 400)
        self.fc2 = nn.Linear(400, 800)
        self.fc3 = nn.Linear(800, 200)
        self.fc4 = nn.Linear(200, 64)
        self.fc5 = nn.Linear(64, 8)
        self.fc6 = nn.Linear(8, 1)
        self.dropout1 = nn.Dropout(0.4)
        self.dropout2 = nn.Dropout(0.3)
        self.dropout3 = nn.Dropout(0.5)
    
    def forward(self, X):
        X = torch.tanh(self.fc1(X))
        X = torch.relu(self.fc2(X))
        X = self.dropout1(X)
        X = torch.relu(self.fc3(X))
        X = self.dropout3(X)
        X = torch.relu(self.fc4(X))
        X = self.dropout2(X)
        X = torch.tanh(self.fc5(X))
        return self.fc6(X)

In [15]:
# Instantiation of the model
torch.manual_seed(42)
model = FFNN_model()
model

FFNN_model(
  (fc1): Linear(in_features=138, out_features=400, bias=True)
  (fc2): Linear(in_features=400, out_features=800, bias=True)
  (fc3): Linear(in_features=800, out_features=200, bias=True)
  (fc4): Linear(in_features=200, out_features=64, bias=True)
  (fc5): Linear(in_features=64, out_features=8, bias=True)
  (fc6): Linear(in_features=8, out_features=1, bias=True)
  (dropout1): Dropout(p=0.4, inplace=False)
  (dropout2): Dropout(p=0.3, inplace=False)
  (dropout3): Dropout(p=0.5, inplace=False)
)

In [16]:
# Number of parameters
num_para = 0
for param in model.parameters():
    print(param.numel())
    num_para += param.numel()
print("----------------------")
print(f'Number of all parameters: \n{num_para}')

55200
400
320000
800
160000
200
12800
64
512
8
8
1
----------------------
Number of all parameters: 
549993


In [17]:
# Objective function and optimmizer
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=1e-3)
# optimizer = optim.SGD(model.parameters(), lr=0.01, momentum=0.9)

## Defining the Training Loop

In [18]:
def training_loop(n_epochs=1000,
                  batch_size=100,
                  optimizer=optimizer, 
                  model=model, 
                  loss_fn=criterion, 
                  train_features=train_features, 
                  test_features=test_features, 
                  train_targets=train_targets, 
                  test_targets=test_targets):
    num_features = train_features.shape[0]
    start_time = time.time()
    all_train_loss, all_test_loss = np.zeros(n_epochs), np.zeros(n_epochs)
    for epoch in range(1, n_epochs +1):
        # Training: 
        epoch_losses = []
        # looping through batches
        for train_features, train_targets in next_batch(train_features=train_features, 
                                                        train_targets=train_targets, batch_size=batch_size): 
            train_preds = model(train_features.float())
            train_loss = loss_fn(train_targets.float(), train_preds.float())
            optimizer.zero_grad()
            train_loss.backward(retain_graph=True)
            optimizer.step()
            
            epoch_losses.append(train_loss.item())
        average_epoch_loss = sum(epoch_losses)/len(epoch_losses)
        
        # Test:
        with torch.no_grad():
            test_preds = model(test_features.float())
            test_loss = loss_fn(test_targets.float(), test_preds.float())
        
        all_train_loss[epoch - 1] = average_epoch_loss
        all_test_loss[epoch - 1] = test_loss.item()
        # Printing the result: 
        if epoch == 1 or epoch % 100 == 0:
            print(f"EPOCH: {epoch:{7}}")
            print(f"MEAN TRAIN LOSS:   {average_epoch_loss:.11f},    TEST LOSS:   {test_loss.item():.11f}")
            print("-----------------------------------------")
    print("The total time = ", np.round(time.time() - start_time, 3), " seconds!")
    return all_train_loss, all_test_loss

# Training the model

In [19]:
losses = training_loop(n_epochs=2000,
                  batch_size=400,
                  optimizer=optimizer, 
                  model=model, 
                  loss_fn=criterion, 
                  train_features=train_features, 
                  test_features=test_features, 
                  train_targets=train_targets, 
                  test_targets=test_targets)

EPOCH:       1
MEAN TRAIN LOSS:   0.86455551237,    TEST LOSS:   0.33597418666
-----------------------------------------
EPOCH:     100
MEAN TRAIN LOSS:   0.31442466378,    TEST LOSS:   0.24364478886
-----------------------------------------
EPOCH:     200
MEAN TRAIN LOSS:   0.27570918202,    TEST LOSS:   0.20247332752
-----------------------------------------
EPOCH:     300
MEAN TRAIN LOSS:   0.24444606900,    TEST LOSS:   0.17533415556
-----------------------------------------
EPOCH:     400
MEAN TRAIN LOSS:   0.21822093427,    TEST LOSS:   0.15231183171
-----------------------------------------
EPOCH:     500
MEAN TRAIN LOSS:   0.19868443906,    TEST LOSS:   0.13571393490
-----------------------------------------
EPOCH:     600
MEAN TRAIN LOSS:   0.18210358918,    TEST LOSS:   0.12263111025
-----------------------------------------
EPOCH:     700
MEAN TRAIN LOSS:   0.16591900587,    TEST LOSS:   0.11634248495
-----------------------------------------
EPOCH:     800
MEAN TRAIN LOSS: 

In [20]:
model.eval()
errors = []
for i in range(n_test):
    targ = test_targets[i].item()
    feat = test_features[i].float().view(1,1,138)
    pred = model(feat).item()
    inaccuracy = abs(1 - pred/targ) * 100
    errors.append(inaccuracy)
    if i%100 == 0:
        print(f"target {targ},    prediction: {pred}\nindex {i}:       inaccuracy: {np.round(inaccuracy, 3)}%")
        print("-----------------------------------------------------------------")

target 2.477397381825853,    prediction: 2.2803971767425537
index 0:       inaccuracy: 7.952%
-----------------------------------------------------------------
target 0.31863985570879155,    prediction: 0.3854336440563202
index 100:       inaccuracy: 20.962%
-----------------------------------------------------------------
target 0.4137940144444872,    prediction: 0.42183196544647217
index 200:       inaccuracy: 1.943%
-----------------------------------------------------------------
target 2.0087731025340507,    prediction: 1.9190704822540283
index 300:       inaccuracy: 4.466%
-----------------------------------------------------------------
target 0.6958696009158427,    prediction: 0.7651911973953247
index 400:       inaccuracy: 9.962%
-----------------------------------------------------------------
target 1.6998357440195866,    prediction: 1.6925427913665771
index 500:       inaccuracy: 0.429%
-----------------------------------------------------------------
target 0.7051056414104

target 0.562145156077087,    prediction: 0.6147424578666687
index 5100:       inaccuracy: 9.357%
-----------------------------------------------------------------
target 0.43347862626721584,    prediction: 0.502723217010498
index 5200:       inaccuracy: 15.974%
-----------------------------------------------------------------
target 0.19202366300995996,    prediction: 0.34809547662734985
index 5300:       inaccuracy: 81.277%
-----------------------------------------------------------------
target 0.7020760873076479,    prediction: 0.699216902256012
index 5400:       inaccuracy: 0.407%
-----------------------------------------------------------------
target 1.368002870748081,    prediction: 1.2430278062820435
index 5500:       inaccuracy: 9.136%
-----------------------------------------------------------------
target 1.9049093936681971,    prediction: 1.9337959289550781
index 5600:       inaccuracy: 1.516%
-----------------------------------------------------------------
target 2.164499

In [21]:
print("Average inaccuracy: ", np.round(sum(errors)/len(errors), 3))

Average inaccuracy:  13.551


In [22]:
torch.save(model, "trained_FFNN_model_fb_media_pagerank_002.pt")