In [1]:
from mygraph import MyGraph
from helpers import *
import pandas as pd

In [2]:
%%time
n= 20000
m1 = 3
m2 = 1
p = 0.5
nxg1 = nx.dual_barabasi_albert_graph(n, m1, m2, p, seed=1, initial_graph=None)
nxg2 = nx.dual_barabasi_albert_graph(n, m1, m2, p, seed=2, initial_graph=None)

Wall time: 370 ms


In [3]:
%%time
myg1 = copy_nx_graph(nxg1)
myg2 = copy_nx_graph(nxg2)

Wall time: 216 ms


In [4]:
df1 = pd.DataFrame(myg1.get_edge_list())
df2 = pd.DataFrame(myg2.get_edge_list())

In [5]:
df1.to_csv("dual_BA_1.csv", columns=None, index=False)
df2.to_csv("dual_BA_2.csv", columns=None, index=False)

In [6]:
%%time
print_dict(myg1.graph_stats())

num_nodes            20000 
num_edges            39959 
nodes_degrees        [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 58, 59, 60, 61, 62, 63, 64, 66, 67, 69, 71, 74, 76, 78, 80, 83, 86, 90, 92, 93, 94, 110, 120, 121, 122, 124, 150, 187, 208, 237, 256, 276, 280] 
average_degree       3.9959 
Wall time: 7.08 s


In [7]:
%%time
print_dict(myg2.graph_stats())

num_nodes            20000 
num_edges            40133 
nodes_degrees        [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 45, 46, 47, 48, 49, 50, 51, 52, 53, 55, 57, 59, 63, 64, 66, 67, 68, 69, 70, 75, 76, 77, 86, 87, 88, 96, 103, 105, 107, 111, 129, 140, 143, 151, 170, 188, 250, 293, 314] 
average_degree       4.0133 
Wall time: 7 s


In [8]:
%%time
# The array of pagerank of vertices of the graph
np_target_page1 = np.array(list(nx.algorithms.link_analysis.pagerank_alg.pagerank(nxg1).values())).reshape(-1,1)
np_target_page1

Wall time: 279 ms


array([[2.89652064e-03],
       [2.94180472e-03],
       [4.01947517e-04],
       ...,
       [3.37041609e-05],
       [1.70165888e-05],
       [3.78052821e-05]])

In [9]:
# Saving the pagerank as a numpy array into a file
np.save("dual_BA_20K_1_pageranks.npy", np_target_page1, allow_pickle=False, fix_imports=True)

In [10]:
%%time
# The array of pagerank of vertices of the graph
np_target_page2 = np.array(list(nx.algorithms.link_analysis.pagerank_alg.pagerank(nxg2).values())).reshape(-1,1)
np_target_page2

Wall time: 132 ms


array([[3.30758022e-03],
       [4.25968932e-04],
       [6.75400628e-04],
       ...,
       [1.78871369e-05],
       [3.60939441e-05],
       [1.77961684e-05]])

In [11]:
# Saving the pagerank as a numpy array into a file
np.save("dual_BA_20K_2_pageranks.npy", np_target_page2, allow_pickle=False, fix_imports=True)

# The order 5 NDFC matrix rep's of random graphs

In [12]:
sp = myg1.starting_points(ratio=1.2, starting_length=1, max_length=20, last_point=50)
sp

[1, 2, 3, 4, 5, 7, 9, 11, 14, 18, 23, 29, 36, 44]

In [13]:
sp_c = [60, 80, 100, 127, 150, 165, 205]

In [14]:
sp_final = sp + sp_c
sp_final

[1,
 2,
 3,
 4,
 5,
 7,
 9,
 11,
 14,
 18,
 23,
 29,
 36,
 44,
 60,
 80,
 100,
 127,
 150,
 165,
 205]

In [15]:
%%time
# producing the order 5 NDFC matrix rep. of nodes of the first random garph w.r.t. the following parameters:
NDFC_dual_BA_20k_1 = NDFC_matrix_rep(myg1, starting_points=sp_final, raw=False, radius=5, decimals=6)

Wall time: 10min 48s


In [16]:
%%time
# producing the order 5 NDFC matrix rep. of nodes of the second random garph w.r.t. the following parameters:
NDFC_dual_BA_20k_2 = NDFC_matrix_rep(myg2, starting_points=sp_final, raw=False, radius=5, decimals=6)

Wall time: 11min 13s


In [17]:
NDFC_dual_BA_20k_2[111:114]

array([[[3.000000e+00, 0.000000e+00, 3.000000e+00, 1.000000e+00,
         9.000000e+00, 2.000000e+00, 0.000000e+00, 2.000000e+00,
         1.000000e+00, 0.000000e+00, 2.000000e+00, 0.000000e+00,
         2.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
         0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
         0.000000e+00],
        [1.480000e+00, 2.000000e-01, 2.080000e+00, 1.160000e+00,
         8.400000e-01, 8.800000e-01, 2.000000e-01, 2.800000e-01,
         4.000000e-01, 3.200000e-01, 1.240000e+00, 1.200000e-01,
         1.200000e-01, 1.200000e-01, 4.000000e-02, 0.000000e+00,
         4.000000e-02, 0.000000e+00, 0.000000e+00, 4.000000e-02,
         4.000000e-02],
        [1.070093e+00, 3.878500e-01, 2.065421e+00, 1.144860e+00,
         1.457944e+00, 8.084110e-01, 5.794390e-01, 5.140190e-01,
         4.953270e-01, 2.616820e-01, 4.672900e-01, 1.308410e-01,
         5.046730e-01, 1.121500e-01, 1.214950e-01, 3.738300e-02,
         2.803700e-02, 5.607500e-02, 9.346

# The shape of the NDFC matrices and saving them

In [18]:
NDFC_dual_BA_20k_1.shape, NDFC_dual_BA_20k_2.shape

((20000, 6, 21), (20000, 6, 21))

In [19]:
np.save("dual_BA_20K_1_NDFC_matrix.npy", NDFC_dual_BA_20k_1, allow_pickle=False, fix_imports=True)
np.save("dual_BA_20K_2_NDFC_matrix.npy", NDFC_dual_BA_20k_2, allow_pickle=False, fix_imports=True)