# Generating two random graphs and computing their closeness centrality and their order 2 RCDF matrix representations

In [1]:
from mygraph import MyGraph
from helpers import *

In [2]:
%%time
n= 20000
m1 = 3
m2 = 1
p = 0.5
nxg1 = nx.dual_barabasi_albert_graph(n, m1, m2, p, seed=1, initial_graph=None)
nxg2 = nx.dual_barabasi_albert_graph(n, m1, m2, p, seed=2, initial_graph=None)

Wall time: 370 ms


In [3]:
%%time
myg1 = copy_nx_graph(nxg1)
myg2 = copy_nx_graph(nxg2)

Wall time: 211 ms


In [4]:
%%time
print_dict(myg1.graph_stats())

num_nodes            20000 
num_edges            39959 
nodes_degrees        [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 58, 59, 60, 61, 62, 63, 64, 66, 67, 69, 71, 74, 76, 78, 80, 83, 86, 90, 92, 93, 94, 110, 120, 121, 122, 124, 150, 187, 208, 237, 256, 276, 280] 
average_degree       3.9959 
Wall time: 8.49 s


In [5]:
%%time
print_dict(myg2.graph_stats())

num_nodes            20000 
num_edges            40133 
nodes_degrees        [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 45, 46, 47, 48, 49, 50, 51, 52, 53, 55, 57, 59, 63, 64, 66, 67, 68, 69, 70, 75, 76, 77, 86, 87, 88, 96, 103, 105, 107, 111, 129, 140, 143, 151, 170, 188, 250, 293, 314] 
average_degree       4.0133 
Wall time: 8.03 s


In [6]:
%%time
# The array of closeness of vertices of the first graph
np_target_closeness1 = np.array(list(nx.closeness_centrality(nxg1).values())).reshape(-1,1)
np_target_closeness1

Wall time: 10min 44s


array([[0.31004279],
       [0.30218186],
       [0.25971715],
       ...,
       [0.21215722],
       [0.17599796],
       [0.18088166]])

In [7]:
%%time
# The array of closeness centrality of vertices of the second graph
np_target_closeness2 = np.array(list(nx.closeness_centrality(nxg2).values())).reshape(-1,1)
np_target_closeness2

Wall time: 9min 16s


array([[0.31145269],
       [0.27027137],
       [0.27182896],
       ...,
       [0.17178467],
       [0.19224817],
       [0.16399344]])

In [8]:
# Saving the closeness centrality arrays as a numpy array into two files
np.save("dual_BA_20K_1_closeness.npy", np_target_closeness1, allow_pickle=False, fix_imports=True)
np.save("dual_BA_20K_2_closeness.npy", np_target_closeness2, allow_pickle=False, fix_imports=True)

# The order 2 RCDF matrix rep's of random graphs

In [9]:
sp = myg1.starting_points(ratio=1.2, starting_length=1, max_length=20, last_point=50)
sp

[1, 2, 3, 4, 5, 7, 9, 11, 14, 18, 23, 29, 36, 44]

In [10]:
sp_c = [60, 80, 100, 127, 150, 165, 205]

In [11]:
sp_final = sp + sp_c
sp_final

[1,
 2,
 3,
 4,
 5,
 7,
 9,
 11,
 14,
 18,
 23,
 29,
 36,
 44,
 60,
 80,
 100,
 127,
 150,
 165,
 205]

In [12]:
%%time
# producing the order 4 RDFC matrix rep. of nodes of the garph w.r.t. the following parameters:
RCDF_dual_BA_20k_1 = CDF_matrix_rep(myg1, starting_points=sp_final, raw=True, radius=2)
RCDF_dual_BA_20k_2 = CDF_matrix_rep(myg2, starting_points=sp_final, raw=True, radius=2)

Wall time: 14.7 s


In [13]:
RCDF_dual_BA_20k_2[111:113]

array([[[  3.,   0.,   3.,   1.,   9.,   2.,   0.,   2.,   1.,   0.,
           2.,   0.,   2.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.],
        [ 37.,   5.,  52.,  29.,  21.,  21.,   5.,   7.,  10.,   8.,
           6.,   3.,   3.,   3.,   1.,   0.,   1.,   0.,   0.,   1.,
           1.]],

       [[  7.,   2.,  10.,   2.,   5.,   3.,   3.,   2.,   3.,   0.,
           3.,   0.,   0.,   0.,   0.,   0.,   2.,   0.,   0.,   0.,
           1.],
        [ 99.,  37., 149.,  76., 105.,  68.,  39.,  33.,  40.,  22.,
          19.,   7.,  14.,   8.,   7.,   3.,   1.,   3.,   1.,   2.,
           2.]]])

# The shape of the RCDF matrix and saving it

In [14]:
RCDF_dual_BA_20k_1.shape, RCDF_dual_BA_20k_2.shape

((20000, 2, 21), (20000, 2, 21))

In [15]:
np.save("dual_BA_20K_1_RDFC_matrix.npy", RCDF_dual_BA_20k_1, allow_pickle=False, fix_imports=True)
np.save("dual_BA_20K_2_RDFC_matrix.npy", RCDF_dual_BA_20k_2, allow_pickle=False, fix_imports=True)

In [16]:
RCDF_dual_BA_20k_2[110:112]

array([[[ 1.,  0.,  2.,  0.,  1.,  3.,  0.,  1.,  4.,  0.,  0.,  0.,
          0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
        [25.,  8., 45., 22., 27., 18., 11.,  8.,  5.,  2.,  2.,  4.,
          1.,  2.,  1.,  1.,  2.,  1.,  0.,  0.,  0.]],

       [[ 3.,  0.,  3.,  1.,  9.,  2.,  0.,  2.,  1.,  0.,  2.,  0.,
          2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [37.,  5., 52., 29., 21., 21.,  5.,  7., 10.,  8.,  6.,  3.,
          3.,  3.,  1.,  0.,  1.,  0.,  0.,  1.,  1.]]])